In [2]:
import numpy as np 
import pandas as pd
import math
import matplotlib.pyplot as plt

In [3]:
## Reading train data
df_train=pd.read_csv('Classification_train.csv')
arr_train=df_train.to_numpy()
print(f"data_train.shape: {arr_train.shape}")
df_train.describe()

data_train.shape: (30000, 785)


label   pixel0   pixel1   pixel2   pixel3   pixel4   pixel5  \
count  30000.000000  30000.0  30000.0  30000.0  30000.0  30000.0  30000.0   
mean       4.498500      0.0      0.0      0.0      0.0      0.0      0.0   
std        2.860875      0.0      0.0      0.0      0.0      0.0      0.0   
min        0.000000      0.0      0.0      0.0      0.0      0.0      0.0   
25%        2.000000      0.0      0.0      0.0      0.0      0.0      0.0   
50%        4.000000      0.0      0.0      0.0      0.0      0.0      0.0   
75%        7.000000      0.0      0.0      0.0      0.0      0.0      0.0   
max        9.000000      0.0      0.0      0.0      0.0      0.0      0.0   

             pixel6        pixel7        pixel8  ...      pixel774  \
count  30000.000000  30000.000000  30000.000000  ...  30000.000000   
mean       0.034000      0.049900      0.087733  ...      0.024233   
std        2.944339      2.909964      4.445233  ...      1.936553   
min        0.000000      0.000000      0.000000  ...      0.000000   
25%        0.000000      0.000000      0.000000  ...      0.000000   
50%        0.000000      0.000000      0.000000  ...      0.000000   
75%        0.000000      0.000000      0.000000  ...      0.000000   
max      255.000000    255.000000    255.000000  ...    255.000000   

           pixel775     pixel776      pixel777      pixel778      pixel779  \
count  30000.000000  30000.00000  30000.000000  30000.000000  30000.000000   
mean       0.031767      0.03130      0.037533      0.007433      0.002767   
std        2.765576      2.07814      2.465453      1.287491      0.479201   
min        0.000000      0.00000      0.000000      0.000000      0.000000   
25%        0.000000      0.00000      0.000000      0.000000      0.000000   
50%        0.000000      0.00000      0.000000      0.000000      0.000000   
75%        0.000000      0.00000      0.000000      0.000000      0.000000   
max      255.000000    150.00000    170.000000    223.000000     83.000000   

           pixel780  pixel781  pixel782  pixel783  
count  30000.000000   30000.0   30000.0   30000.0  
mean       0.007567       0.0       0.0       0.0  
std        1.310585       0.0       0.0       0.0  
min        0.000000       0.0       0.0       0.0  
25%        0.000000       0.0       0.0       0.0  
50%        0.000000       0.0       0.0       0.0  
75%        0.000000       0.0       0.0       0.0  
max      227.000000       0.0       0.0       0.0  

[8 rows x 785 columns]

In [4]:
## Reading test data
df_test=pd.read_csv('classification_test.csv')
arr_test=df_test.to_numpy()
print(f"data_train.shape: {arr_test.shape}")
df_test.describe()

data_train.shape: (10000, 785)


ID   pixel0   pixel1   pixel2   pixel3   pixel4   pixel5  \
count  10000.00000  10000.0  10000.0  10000.0  10000.0  10000.0  10000.0   
mean    9945.83690      0.0      0.0      0.0      0.0      0.0      0.0   
std     5787.98325      0.0      0.0      0.0      0.0      0.0      0.0   
min        1.00000      0.0      0.0      0.0      0.0      0.0      0.0   
25%     4895.00000      0.0      0.0      0.0      0.0      0.0      0.0   
50%     9968.00000      0.0      0.0      0.0      0.0      0.0      0.0   
75%    14933.00000      0.0      0.0      0.0      0.0      0.0      0.0   
max    19996.00000      0.0      0.0      0.0      0.0      0.0      0.0   

        pixel6   pixel7        pixel8  ...      pixel774      pixel775  \
count  10000.0  10000.0  10000.000000  ...  10000.000000  10000.000000   
mean       0.0      0.0      0.100800  ...      0.018000      0.044300   
std        0.0      0.0      5.007429  ...      1.277748      3.153019   
min        0.0      0.0      0.000000  ...      0.000000      0.000000   
25%        0.0      0.0      0.000000  ...      0.000000      0.000000   
50%        0.0      0.0      0.000000  ...      0.000000      0.000000   
75%        0.0      0.0      0.000000  ...      0.000000      0.000000   
max        0.0      0.0    255.000000  ...     98.000000    247.000000   

         pixel776  pixel777  pixel778  pixel779  pixel780  pixel781  pixel782  \
count  10000.0000   10000.0   10000.0   10000.0   10000.0   10000.0   10000.0   
mean       0.0067       0.0       0.0       0.0       0.0       0.0       0.0   
std        0.6700       0.0       0.0       0.0       0.0       0.0       0.0   
min        0.0000       0.0       0.0       0.0       0.0       0.0       0.0   
25%        0.0000       0.0       0.0       0.0       0.0       0.0       0.0   
50%        0.0000       0.0       0.0       0.0       0.0       0.0       0.0   
75%        0.0000       0.0       0.0       0.0       0.0       0.0       0.0   
max       67.0000       0.0       0.0       0.0       0.0       0.0       0.0   

       pixel783  
count   10000.0  
mean        0.0  
std         0.0  
min         0.0  
25%         0.0  
50%         0.0  
75%         0.0  
max         0.0  

[8 rows x 785 columns]

In [8]:
## Forming Input and Output labels of training set
x_train=arr_train[:,1:]
print(x_train.shape)
print(x_train)

y_train=arr_train[:,0]
print(y_train.shape)
print(y_train)

(30000, 784)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(30000,)
[0 8 1 ... 9 3 9]


In [7]:
## Forming Input and Output labels of test set
x_test=arr_test[:,1:]
print(x_test.shape)
print(x_test)

y_test=arr_test[:,0]
print(y_test.shape)
print(y_test)

(10000, 784)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(10000,)
[15795   860  5390 ...   634 10057 13345]


In [15]:
def KNN(x,y,test_ex,k):
    m=x.shape[0]  
    n=x.shape[1]  
    dist=np.zeros(m)
    dist=np.sum((x-np.tile(test_ex,(m,1)))**2,axis=1)
    idx=np.argsort(dist)
    required_idx=idx[0:k]
    nearest_k=np.zeros(k)
    for i in range(k):
        nearest_k[i]=y[required_idx[i]]
    values,c=np.unique(nearest_k,return_counts=True)
    p=np.argmax(c)
    pred=values[p]
    return pred    

In [10]:
def accuracy(y_pred,y):
    return((np.sum(y_pred==y))/y.shape)*100     

In [11]:
x_cv=x_train[20000:30000,:]
print(x_cv)
y_cv=y_train[20000:30000]
print(y_cv)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[8 0 4 ... 9 3 9]


In [18]:
y_predicted=np.zeros(10000)
for i in range(10000):
    y_predicted[i]=KNN(x_train,y_train,x_cv[i],3)
print(y_predicted) 

[8. 0. 4. ... 9. 3. 9.]


In [20]:
accuracy(y_predicted,y_cv)

array([99.12])

In [21]:
y_pred_test=np.zeros(10000)
for i in range(10000):
    y_pred_test[i]=KNN(x_train,y_train,x_test[i],3)
print(y_pred_test) 
csv_file_path = 'KNN_Predicted.csv'
np.savetxt(csv_file_path, y_pred_test, delimiter=',')
print(f"Array has been saved to {csv_file_path}")

[0. 4. 5. ... 0. 8. 4.]
Array has been saved to KNN_Predicted.csv
